services:

  mssql:
    container_name: betfriends-sqlserv
    hostname: betfriends-sqlserv
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Password!'
    ports: 
      - "1433:1433"