version: '3.9'
services:
  SQLServer:
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password!
   ports:
     - 1434:1434/tcp
   container_name: sqlserv-betfriends